language: java
jdk:
  - openjdk17

# Git Push할 Branch
branches:
  only:
    - deploy

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE eight;'

install:
  - chmod +x ./gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# Gradle 빌드 명령어 업데이트
script:
  - ./gradlew clean build
  - ./gradlew bootRun

env:
  - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/eight
    SPRING_DATASOURCE_USERNAME=eight
    SPRING_DATASOURCE_PASSWORD=eight1886!

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yewonchoi@ewhain.net
