language: java
jdk:
  - openjdk17

# Git Push할 Branch
branches:
  only:
    - deploy

# gradlew 권한 추가
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# Gradle 빌드 명령어 업데이트
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yewonchoi@ewhain.net