version: 0.0
os : linux

files:
  - source: / # 인스턴스에 복사할 디렉토리 경로
    destination: /home/ubuntu/app # 인스턴스에서 파일이 복사되는 위치
    overwrite: yes # 복사할 위치에 파일 있는 경우 대체

permissions:
  - object: / # 권한이 지정되는 파일 or 디렉토리
    pattern: "**" # 매칭되는 패턴에만 권한 부여
    owner: ubuntu # object 소유자
    group: ubuntu # object의 그룹 이름