name: ArtHunter server CI/CD

# Controls when the workflow will run
on:
  push:
    branches: 
      - ci-githubaction/yeni
  pull_request:
    types: 
      - closed
    branches: 
      - ci-githubaction/yeni
    
env:
  S3_BUCKET_NAME: cointalk-deploy

permissions:
  contents: read

  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: 'utf8'
        mysql database: 'eight'
        mysql user: 'eight'
        mysql password: 'eight1886!'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
